theme: minima
title: BLOG
author: imlakshay08
email: tyagilakshay119@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Blog for Ethical Hacking: Ethical hacking is a process of detecting vulnerabilities in an application, system, or organization's infrastructure that an attacker can use to exploit an individual or organization. They use this process to prevent cyberattacks and security breaches by lawfully hacking into the systems and looking for weak points.

# social links
imLakshay08: https://twitter.com/imLakshay08 # DO NOT include the @ character, or else the build will fail!
imlakshay08: https://github.com/imlakshay08 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
